# platform :ios, '8.0'

pod 'Masonry'
pod 'PDSSetting_objc', :git => 'https://github.com/w91379137/PDSSetting_objc.git'
pod 'PDSSafeKVO_objc', :git => 'https://github.com/w91379137/PDSSafeKVO_objc.git'