# platform :ios, '8.0'


pod 'Masonry'
#https://github.com/SnapKit/Masonry

pod 'FontAwesomeKit', '~> 2.2.0'
#https://github.com/PrideChung/FontAwesomeKit
#https://fortawesome.github.io/Font-Awesome/

pod 'AFNetworking'
#https://github.com/AFNetworking/AFNetworking

pod 'FMDB'
#https://github.com/ccgus/fmdb

pod 'JHChainableAnimations', '~> 1.3.0'
#https://github.com/jhurray/JHChainableAnimations

pod 'MBProgressHUD'
#https://github.com/jdg/MBProgressHUD

pod 'SDWebImage', :inhibit_warnings => true
#https://github.com/rs/SDWebImage

pod 'UIActivityIndicator-for-SDWebImage'
#https://github.com/JJSaccolo/UIActivityIndicator-for-SDWebImage

pod 'EZAudio'
#https://github.com/syedhali/EZAudio

pod 'HCYoutubeParser'
#https://github.com/hellozimi/HCYoutubeParser

pod 'XCDYouTubeKit', '~> 2.5'
#https://github.com/0xced/XCDYouTubeKit

pod 'PDSSetting_objc', :git => 'https://github.com/w91379137/PDSSetting_objc.git'
pod 'PDSImageControl', :git => 'https://github.com/w91379137/PDSImageControl.git'
pod 'PDSSafeKVO_objc', :git => 'https://github.com/w91379137/PDSSafeKVO_objc.git'
pod 'PDSEnvironment_objc', :git => 'https://github.com/w91379137/PDSEnvironment_objc.git'
pod 'PDSIBDesignableView_objc', :git => 'https://github.com/w91379137/PDSIBDesignableView_objc.git'